package main

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"strings"
	"text/template"
)

// runSetup handles `forge-proxy setup <subcommand>`. Today there's only
// the `systemd` subcommand; future flavours (e.g. openrc, launchd) slot in
// here without changing the dispatch shape.
func runSetup(args []string) error {
	if len(args) == 0 {
		return fmt.Errorf("usage: forge-proxy setup <subcommand>\n\nsubcommands:\n  systemd   create the forge-proxy user, /var/lib/forge-proxy, the\n            systemd unit, then daemon-reload + enable --now")
	}
	switch args[0] {
	case "systemd":
		return runSetupSystemd(args[1:])
	default:
		return fmt.Errorf("unknown setup subcommand: %s", args[0])
	}
}

// systemdUnitTemplate is the unit file written to
// /etc/systemd/system/forge-proxy.service. The path to the binary is
// computed at runtime so the unit is correct whether the operator
// installed via curl|sh to /usr/local/bin or pulled the binary out of a
// release tarball into ~/bin.
//
// Hardening directives match deploy/forge-proxy.service in the source
// tree; the two should stay in sync. The setup subcommand is the
// runtime-generated half, deploy/ is the human-readable / git-tracked
// reference.
const systemdUnitTemplate = `[Unit]
# Generated by ` + "`forge-proxy setup systemd`" + `. Edit and re-run to update,
# or hand-edit this file (re-generation will overwrite).
Description=Forge Utah auth proxy
Documentation=https://github.com/forgeutah/forge-proxy
After=network-online.target tailscaled.service
Wants=network-online.target

[Service]
Type=simple
User={{.User}}
Group={{.Group}}

EnvironmentFile={{.EnvFile}}

ExecStart={{.BinaryPath}}

KillSignal=SIGTERM
TimeoutStopSec=31s

Restart=on-failure
RestartSec=5s

# Hardening — the binary needs network access (Slack OIDC + Tailscale
# upstreams), read access to its env file, and write access to its data
# directory. Everything else is locked down.
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths={{.DataDir}}
PrivateTmp=true
PrivateDevices=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
RestrictNamespaces=true
RestrictRealtime=true
LockPersonality=true
MemoryDenyWriteExecute=true

[Install]
WantedBy=multi-user.target
`

// systemdSetupParams holds the variables substituted into
// systemdUnitTemplate. Exposed for tests.
type systemdSetupParams struct {
	User       string
	Group      string
	BinaryPath string
	EnvFile    string
	DataDir    string
	UnitPath   string
}

// defaultSystemdParams returns the conventional set of values: the
// forge-proxy user, /usr/local/bin/forge-proxy, /etc/forge-proxy.env,
// /var/lib/forge-proxy. The actual binary path is taken from the running
// process's executable path so a binary at /opt/forge/forge-proxy
// installs a unit pointing at /opt/forge/forge-proxy.
func defaultSystemdParams() (systemdSetupParams, error) {
	binPath, err := os.Executable()
	if err != nil {
		return systemdSetupParams{}, fmt.Errorf("resolve own path: %w", err)
	}
	return systemdSetupParams{
		User:       "forge-proxy",
		Group:      "forge-proxy",
		BinaryPath: binPath,
		EnvFile:    "/etc/forge-proxy.env",
		DataDir:    "/var/lib/forge-proxy",
		UnitPath:   "/etc/systemd/system/forge-proxy.service",
	}, nil
}

// renderSystemdUnit fills systemdUnitTemplate with the given params.
// Pure function so tests can assert on the output without touching the
// filesystem or systemd.
func renderSystemdUnit(p systemdSetupParams) (string, error) {
	t, err := template.New("unit").Parse(systemdUnitTemplate)
	if err != nil {
		return "", err
	}
	var sb strings.Builder
	if err := t.Execute(&sb, p); err != nil {
		return "", err
	}
	return sb.String(), nil
}

// runSetupSystemd is the actual subcommand: create user/group, data
// directory, write the unit, daemon-reload, enable + start.
//
// Idempotent: if the user/group already exists, skip creation; if the
// directory already exists, skip creation; if the unit already exists,
// overwrite (with a warning, since hand-edits will be lost).
func runSetupSystemd(args []string) error {
	if len(args) > 0 {
		return fmt.Errorf("setup systemd takes no positional arguments; got %v", args)
	}

	if os.Geteuid() != 0 {
		return errors.New("setup systemd must run as root (re-run with sudo)")
	}

	if !commandAvailable("systemctl") {
		return errors.New("systemctl not found on PATH — this host does not look like a systemd machine")
	}

	params, err := defaultSystemdParams()
	if err != nil {
		return err
	}

	// 1. Group + user. systemd's User= directive requires both to exist.
	if err := ensureSystemGroup(params.Group); err != nil {
		return err
	}
	if err := ensureSystemUser(params.User, params.Group); err != nil {
		return err
	}

	// 2. Data directory.
	if err := ensureDataDir(params.DataDir, params.User, params.Group); err != nil {
		return err
	}

	// 2b. Env file permissions. install.sh writes /etc/forge-proxy.env
	// as mode 0600 root:root (safe default before forge-proxy group
	// exists). Now that the group exists, fix to 0640 root:forge-proxy
	// so `sudo -u forge-proxy forge-proxy admin ...` invocations can
	// read it. systemd's EnvironmentFile= directive runs as root before
	// dropping privileges so it works either way; this is purely for
	// the ad-hoc admin path.
	if err := fixEnvFilePermissions(params.EnvFile, params.Group); err != nil {
		// Non-fatal — the env file might not exist yet (operator
		// hasn't installed it), or might be at a non-default path
		// (FORGE_PROXY_ENV_FILE override). Surface a warning but keep
		// going; the systemd service still starts.
		fmt.Fprintf(os.Stderr, "warning: %v\n", err)
	}

	// 3. Unit file.
	unit, err := renderSystemdUnit(params)
	if err != nil {
		return fmt.Errorf("render unit: %w", err)
	}
	if _, err := os.Stat(params.UnitPath); err == nil {
		fmt.Fprintf(os.Stderr, "warning: %s already exists; overwriting (hand-edits will be lost)\n", params.UnitPath)
	}
	if err := os.WriteFile(params.UnitPath, []byte(unit), 0o644); err != nil {
		return fmt.Errorf("write unit %s: %w", params.UnitPath, err)
	}
	fmt.Printf("wrote %s\n", params.UnitPath)

	// 4. Reload + enable + start.
	if err := runCommand("systemctl", "daemon-reload"); err != nil {
		return err
	}
	if err := runCommand("systemctl", "enable", "--now", "forge-proxy"); err != nil {
		return err
	}

	// 5. Status check.
	fmt.Println()
	fmt.Println("forge-proxy is enabled and started. Service status:")
	_ = runCommand("systemctl", "--no-pager", "status", "forge-proxy")

	// 6. Env-file reminder. The unit references /etc/forge-proxy.env via
	// EnvironmentFile=; if the operator hasn't created it yet, the
	// service will fail to start with a clear error.
	if _, err := os.Stat(params.EnvFile); errors.Is(err, os.ErrNotExist) {
		fmt.Println()
		fmt.Printf("note: %s does not exist yet. Create it from .env.example:\n", params.EnvFile)
		fmt.Printf("  sudo install -m 0640 -o root -g %s .env.example %s\n", params.Group, params.EnvFile)
		fmt.Printf("  sudo $EDITOR %s\n", params.EnvFile)
		fmt.Println("Then restart the service:")
		fmt.Println("  sudo systemctl restart forge-proxy")
	}

	return nil
}

// ensureSystemGroup creates the named group if it doesn't exist. Uses
// /usr/sbin/groupadd or BSD-style groupadd; both accept --system on
// modern distros.
func ensureSystemGroup(name string) error {
	if err := runCommand("getent", "group", name); err == nil {
		fmt.Printf("group %s already exists\n", name)
		return nil
	}
	if err := runCommand("groupadd", "--system", name); err != nil {
		return fmt.Errorf("create group %s: %w", name, err)
	}
	fmt.Printf("created group %s\n", name)
	return nil
}

// ensureSystemUser creates the named system user if it doesn't exist,
// member of the given group, no home directory, nologin shell.
func ensureSystemUser(name, group string) error {
	if err := runCommand("getent", "passwd", name); err == nil {
		fmt.Printf("user %s already exists\n", name)
		return nil
	}
	if err := runCommand("useradd",
		"--system",
		"--gid", group,
		"--no-create-home",
		"--shell", "/usr/sbin/nologin",
		name,
	); err != nil {
		return fmt.Errorf("create user %s: %w", name, err)
	}
	fmt.Printf("created user %s\n", name)
	return nil
}

// fixEnvFilePermissions chgrp's the env file to the forge-proxy group
// and bumps mode to 0640 (group-readable). install.sh writes it as
// 0600 root:root initially because the group doesn't exist at that
// point; this is the post-setup fix that lets the forge-proxy user
// read the file directly (e.g. for ad-hoc `sudo -u forge-proxy
// forge-proxy admin ...` invocations).
//
// Returns nil silently if the env file doesn't exist — the operator
// may not have installed it yet, or may be using a non-default
// location via FORGE_PROXY_ENV_FILE. Returns an error only if the
// file exists but chown/chmod fails.
func fixEnvFilePermissions(envFile, group string) error {
	info, err := os.Stat(envFile)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("stat env file %s: %w", envFile, err)
	}
	if !info.Mode().IsRegular() {
		return fmt.Errorf("%s exists but is not a regular file", envFile)
	}
	// chgrp via the OS so the group lookup actually works on this host
	// (Go's syscall.Chown wants numeric IDs; shelling out lets us pass
	// the group name and have getpwnam/getgrnam resolve it).
	if err := runCommand("chgrp", group, envFile); err != nil {
		return fmt.Errorf("chgrp %s %s: %w", group, envFile, err)
	}
	if err := os.Chmod(envFile, 0o640); err != nil {
		return fmt.Errorf("chmod 0640 %s: %w", envFile, err)
	}
	fmt.Printf("fixed permissions on %s (root:%s, mode 0640)\n", envFile, group)
	return nil
}

// ensureDataDir creates the data directory owned by user:group with
// 0750 permissions. Idempotent: if it already exists, we leave existing
// ownership and permissions alone (operator may have customised them).
func ensureDataDir(path, user, group string) error {
	if info, err := os.Stat(path); err == nil {
		if !info.IsDir() {
			return fmt.Errorf("%s exists but is not a directory", path)
		}
		fmt.Printf("data dir %s already exists\n", path)
		return nil
	}
	// install -d sets owner/group/mode atomically.
	if err := runCommand("install", "-d",
		"-o", user, "-g", group, "-m", "0750", path,
	); err != nil {
		return fmt.Errorf("create data dir %s: %w", path, err)
	}
	fmt.Printf("created %s (owner %s:%s, mode 0750)\n", path, user, group)
	return nil
}

// runCommand runs an external command, surfacing stdout/stderr live so
// the operator sees what systemd/useradd are doing.
func runCommand(name string, args ...string) error {
	cmd := exec.Command(name, args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// commandAvailable reports whether name is on PATH.
func commandAvailable(name string) bool {
	_, err := exec.LookPath(name)
	return err == nil
}
